### ISSUE TITLE
Need to start service manually

### ISSUE THREAD

**Issue by wvengen** [majido/clipper#2]
It took me some time to figure out that the service wasn't started automatically after installation. And some more time to figure out that I had to run

```
am startservice ca.zgrs.clipper/.ClipboardService
```

to do so. After that I could use the broadcast commands and have them function.

Suggestion: make service auto-start and/or document this command in the README.

**Comment by majido** [comment]
This is a great suggestion. I will look into finding out if it is possible to make it auto-start.

**Comment by majido** [comment]
Unfortunately it is not possible to start a service automatically after application is installed. This is due to security features on android platform. So to make things easier I did these two:
1- Added a single page to the application which makes it easier to launch the application and start the service from android user interface.
2-  Updated README with the command to start the service from adb shell.

If you are curious here you can find more about Android limitation on auto-starting the service after apk installation: http://stackoverflow.com/a/8535062

**Comment by wvengen** [comment]
Sounds great, thanks!
